# Specify the parent image from which we build
FROM python:3.12-rc-slim-buster

# Set the working directory
WORKDIR /app

# Copy source code to image
COPY --from=project . .

# Install required packages
RUN echo 'Installing requirements in image' &&\
    pip3 install -r /app/requirements.txt &&\
    rm -rf /var/lib/apt/lists/* &&\
    apt-get clean &&\
    apt-get autoclean &&\
    apt-get autoremove

LABEL description="ctrlX Datalayer MQTT UI"
LABEL maintainer="S-Gilk <https://github.com/S-Gilk>"

# Run the application
CMD ["python3", "/app/main.py"]